spring.application.name=FitPlanner

server.port=${PORT:8080}
server.address=0.0.0.0

management.endpoint.health.probes.enabled=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/FitPlanner?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Session
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=30m

# Actuator
management.endpoints.web.exposure.include=health,info

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.mvc.throw-exception-if-no-handler-found=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

app.security.admin-code=${ADMIN_CODE}
app.security.trainer-code=${TRAINER_CODE}
