spring.application.name=FitPlanner

server.port=${PORT:8080}
server.address=0.0.0.0

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/FitPlanner?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Session
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=30m

# Actuator
management.endpoints.web.exposure.include=health,info

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

app.security.admin-code=${ADMIN_CODE}
app.security.trainer-code=${TRAINER_CODE}
